### ISSUE TITLE
Fail to connect to app after launch

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode-spring-boot-dashboard#166] opened 2022-05-06 08:24 UTC
Try launch the app using the dashboard:
![image](https://user-images.githubusercontent.com/16755094/167094788-15ab1b9f-b57c-4a1c-a9e4-cb11f239b47a.png)

And the dashboard keeps showing the spinning icon without actually connecting to the app
![image](https://user-images.githubusercontent.com/16755094/167094657-1c6ad5e5-716e-4ed6-b1d1-4b7258aed51a.png)

From the debug console we can tell that the app was already started:
![image](https://user-images.githubusercontent.com/16755094/167095025-365bf533-5e21-474f-bb55-0d097e2aa425.png)

A sidenote that the app can be stopped using the stop button on the dashboard:
![image](https://user-images.githubusercontent.com/16755094/167095160-8d36eba0-7365-4585-acb2-5ba9ed31c296.png)

Launch = run | debug

**Comment by duoduobingbing** [comment] 2022-06-11 20:31
I have the same problem. It happens with v0.4.2022061100 and v0.4.0 and with and without having
```
"java.configuration.runtimes": [

    {
      "name": "JavaSE-17",
      "path": "C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.3.7-hotspot",
      "default": true
    }
]
```
enabled. 

Some details on my setup: I use the newest Version of VSCode with Windows 10.

Starting command Line:
```
& 'C:\Program Files\Eclipse Adoptium\jdk-17.0.3.7-hotspot\bin\java.exe' '-Dcom.sun.management.jmxremote' '-Dcom.sun.management.jmxremote.port=50286' '-Dcom.sun.management.jmxremote.authenticate=false' '-Dcom.sun.management.jmxremote.ssl=false' '-Djava.rmi.server.hostname=localhost' '-Dspring.application.admin.enabled=true' '-Dspring.jmx.enabled=true' '-Dspring.boot.project.name=de-demo' '-XX:+ShowCodeDetailsInExceptionMessages' '@C:\Users\someuser\AppData\Local\Temp\cp_25x8905b03ze2yat69ecn25nh.argfile' 'com.example.exampleapp.DemoApplication'
```

It never connects and just always says:                                                                                                               
*Failed to refresh live data from process 7432 after retries: 10*

The last version that works for me and connects is v0.3.1.

**Comment by Eskibear** [comment] 2022-06-12 15:47
> Failed to refresh live data from process 7432 after retries: 10
> The last version that works for me and connects is v0.3.1.

It's implemented in https://github.com/spring-projects/sts4/tree/main/vscode-extensions/vscode-spring-boot , so version of spring-boot-dashboard extension should make no difference to the behavior.

> Maybe a hint should be added that the live connect depends on having

Good idea. Will think about how to notify users about this when actuator is not enabled.

> Having anything else than "console": "integratedTerminal" configured in launch.json causes the live connection to fail as well.

Looks like live connection is not auto-connected in such cases. Will investigate it and sync with vscode-spring-boot authors.

**Comment by utkuaslan85** [comment] 2022-06-23 09:23
I have the exact same problem.  None of the hints in this thread worked for me. Downgrading to v0.3.1 is the only working solution in my case.

**Comment by Eskibear** [comment] 2022-06-23 15:07
@utkuaslan85 Do you have customized launch configuration file? Try removing `.vscode/launch.json`. See if that works.

**Comment by utkuaslan85** [comment] 2022-06-24 08:25
> Do you have customized launch configuration file? Try removing .vscode/launch.json. See if that works.

@Eskibear That solved the problem. Thank you very much.

**Comment by Eskibear** [comment] 2022-06-27 07:29
Turns out the root cause is: upstream vscode-spring-boot extension fails to auto connect the corresponding live process, when you launch your apps with `"console": "internalConsole"`. See https://github.com/spring-projects/sts4/issues/794 . Hopefully it'll get fixed soon.

## Current workaround for you to take:
- Option A) Remove "console" section or the whole launch.json, and re-run it. Default console is integratedTerminal, which should work. 
- Option B) Manually select and connect corresponding process, via command `Spring Boot: Manage Live Spring Boot Process Connections`.

## workaround we can take:
To mitigate the issue before it's fixed in upstream, probably we can force it to run in `integratedTerminal` if you launch your app from the dashboard.

**Comment by Eskibear** [comment] 2022-09-27 06:25
fixed in upstream.

**Closed by Eskibear** 2022-09-27 06:25 UTC
Labels: bug, external dependency
