### ISSUE TITLE
Spring boot Dashboard keep spinning

### ISSUE THREAD

**Issue by kiendn1999** [microsoft/vscode-spring-boot-dashboard#216] opened 2022-08-30 18:20 UTC
![image](https://user-images.githubusercontent.com/57392834/187514377-4359fe9e-3a02-4ee0-ac8a-ef61b8e9717b.png)

**Comment by Eskibear** [comment] 2022-08-31 01:21
Strongly recommend that you try the pre-release version, to verify whether the coming release will work for you. Let me know if that works.

**Comment by kiendn1999** [comment] 2022-08-31 02:43
> Strongly recommend that you try the pre-release version, to verify whether the coming release will work for you. Let me know if that works.
![image](https://user-images.githubusercontent.com/57392834/187580957-1ce5d050-6b41-4c33-a70c-02e804481fed.png)

I followed your instructions but it still doesn't work :(

**Comment by Eskibear** [comment] 2022-08-31 02:50
Good catch. Might be some edge case.
 
Looks like it's a simple spring-boot project created from Initializr, is it? How do you create your project, any customization?
And how you do run it? From `Run|Debug` in DemoApplication.java, or from `Apps` view?

**Comment by Eskibear** [comment] 2022-08-31 02:57
I somehow figure out the culprit from the screenshot above,  some mismatch of the internal data structure of the app instance. For me to easily reproduce it, can you describe how you add Actuator and run your projects, and the order?

**Comment by Eskibear** [comment] 2022-08-31 03:02
Please also let me know version of extension `Spring Boot Tools`.

**Comment by Eskibear** [comment] 2022-08-31 03:15
I managed to reproduce it. 

1. with setting `"java.configuration.updateBuildConfiguration": "automatic"`
2. start with a project without actuator, run it
3. beans/mappings view change to a new guide view, click "Enable Actuator"
4. Click "Save and Re-run", it has chance to reproduce the bug shown in https://github.com/microsoft/vscode-spring-boot-dashboard/issues/216#issuecomment-1232385771


@kiendn1999 This should randomly occur, and it should get back to normal when you re-run your projects. Can you stably reproduce it every time you run it?

**Comment by kiendn1999** [comment] 2022-08-31 03:47
> I somehow figure out the culprit from the screenshot above, some mismatch of the internal data structure of the app instance. For me to easily reproduce it, can you describe how you add Actuator and run your projects, and the order?

https://user-images.githubusercontent.com/57392834/187588409-a5a28779-107c-4eaf-93a3-edd7357bc91a.mp4

**Comment by Eskibear** [comment] 2022-08-31 04:34
Thank you for the information, but I still cannot reproduce it on my side.



https://user-images.githubusercontent.com/2351748/187593396-e03c3924-3b6d-42a5-8acc-b35fdfda179c.mp4


I'll leave this issue open until I find the way to reproduce it.

**Comment by kiendn1999** [comment] 2022-08-31 06:13
> Thank you for the information, but I still cannot reproduce it on my side.
> 
>  not-reproduce.mp4 
> I'll leave this issue open until I find the way to reproduce it.

![image](https://user-images.githubusercontent.com/57392834/187606441-42d4a3dd-b478-4b0f-927b-1f26f011ef92.png)
It works fine if I click here, but when I click on Run button in Spring boot dashboard it doesn't work

**Comment by Eskibear** [comment] 2022-08-31 06:38
Running from dashboard, it will honor existing launch configs with the same main class. Running from button in editor title bar, it's the same with pressing <F5>, regarded as a pure Java project.

I guess it can be some malformed launch configs being honored when it's launched from dashboard. If so, you can simply remove the file and re-run it from dashboard, which will generate a new one for your project.

If that works, can you share previous malformed content of `.vscode/launch.json`? That would be very helpful for us to polish it.

**Comment by kiendn1999** [comment] 2022-08-31 08:19
> Running from dashboard, it will honor existing launch configs with the same main class. Running from button in editor title bar, it's the same with pressing , regarded as a pure Java project.
> 
> I guess it can be some malformed launch configs being honored when it's launched from dashboard. If so, you can simply remove file `.vscode/launch.json` and re-run it from dashboard, which will generate a new one for your project.
> 
> If that works, can you share previous malformed content of `.vscode/launch.json`? That would be very helpful for us to polish it.
I deleted the launch.json file but it still doesn't work :v

**Comment by kiendn1999** [comment] 2022-08-31 08:20
> Running from dashboard, it will honor existing launch configs with the same main class. Running from button in editor title bar, it's the same with pressing , regarded as a pure Java project.
> 
> I guess it can be some malformed launch configs being honored when it's launched from dashboard. If so, you can simply remove file `.vscode/launch.json` and re-run it from dashboard, which will generate a new one for your project.
> 
> If that works, can you share previous malformed content of `.vscode/launch.json`? That would be very helpful for us to polish it.

I deleted the launch.json file but it still doesn't work :v

**Comment by Eskibear** [comment] 2022-09-01 03:43
When an app is running with actuator, live process is auto-connected to provide live information. 

![image](https://user-images.githubusercontent.com/2351748/187825810-c0b04209-fd06-4473-8db0-a3dd177ccd32.png)

In your case, `processName` from live connection is "Unknown", which is expected to be fully qualified name of the main class. Thus it failed to find corresponding project and update its status. In this extension's view, "demo" project was launched but not completely running, but another "Unknown" project is running because it received the signal.

Two follow-up actions in my mind:
- For upstream extension [spring-tools](https://github.com/spring-projects/sts4/tree/main/vscode-extensions/vscode-spring-boot), we want to figure out why and when the processName is "Unknown". 
- For this extension, we need a more reliable way to find corresponding project in such cases.

**Comment by jxcodes** [comment] 2022-09-19 07:05
I had the same issue, I tried going back to the previous version and it worked fine!  

![image](https://user-images.githubusercontent.com/37024829/190965443-2fc14963-bc4f-4217-a8fa-d263357054cd.png)

![image](https://user-images.githubusercontent.com/37024829/190965132-276c7d50-8f15-416f-b7d0-1dfcb56d17f2.png)

**Comment by martinlippert** [comment] 2024-03-28 14:58
I am using the latest version of all the extensions (Spring Boot Tools + Dashboard + Java, etc) and I have a pet clinic sample project in my workspace (which has actuators on the classpath) and "usually", it works and there is no spinning wheel on the dashboard in front of the app once the app fully started. But sometimes, this issue still appears.

My trial-and-error tests show:
- when I start VSCode with the project opened and press "run" on the dashboard view, it always works
- when I start VSCode with  the project opened and press "run" on the code lens of the main class or the "run" button at the top of the editor, it doesn't work when started for the first time. Live beans show up, but the spinning wheel keeps running in front of the app in the dashboard apps view.
- subsequent runs keep working fine and the spinning wheel disappears.

I can reproduce this behavior every time I started VSCode, have the project opened, and press "run" on those locations. But once the app started at least once, the problem goes away. All subsequent starts of the app work fine with regards to the spinning wheel in the dashboard view.

@BoykoAlex, would be awesome if you could have a look at this.

**Comment by BoykoAlex** [comment] 2024-03-28 20:49
The issue is the following:
1. Custom debug event received with the PID. Find boot_app in the list using matching against active session name and current debug session name. At this point `activeSessionName` is `undefined` therefore no PID assigned to `BootApp`
2. Debug Session Started event received and assigns session name to `activeSessionName` in the `BootApp` found by matching project name in `BootApp` and `DebugSession` config.
3. Live Process connected event received. `LiveDataController.updateProcessInfo(...)` is invoked but it cannot update the running state for the `BootApp` because it attempts to find the app by PID which hasn't been assigned.

That was the very first app start. Consecutive app starts seem to work only because the `activeSessionName` is not reset. It stays the same after the first launch. Consequently following launches of the same app would have PID assigned properly in step 1 and then running state updated properly in step 3.

See my PR (#338) to fix the issue.

**Closed** 2024-04-02 11:19 UTC
Labels: bug
