### ISSUE TITLE
Dashboard. Beans and endpoints duplicates

### ISSUE THREAD

**Issue by Sorreldd** [microsoft/vscode-spring-boot-dashboard#324] opened 2023-07-03 13:56 UTC
![image](https://github.com/microsoft/vscode-spring-boot-dashboard/assets/2545203/907235c0-afa0-4072-8365-e5efb434e2e8)

I don't know what information will be useful.
Win 10, 
vscode 1.79.2, 
maven 3.9.3, 
jdk 17(build 17+35-LTS-2724), 
spring boot parent 2.7.13 with spring-cloud-dependecies 2021.0.7 and openfeign
this is NOT pre release version

**Comment by martinlippert** [comment] 2024-04-05 16:59
Can you provide a sample project that can help us to reproduce this issue? I guess the underlying issue should be fixed in https://github.com/spring-projects/sts4/, but a sample project to see this issue in action would greatly help to identify the root cause.

**Comment by Sorreldd** [comment] 2024-04-08 07:33
> Can you provide a sample project that can help us to reproduce this issue? I guess the underlying issue should be fixed in https://github.com/spring-projects/sts4/, but a sample project to see this issue in action would greatly help to identify the root cause.

Hello, you can use this example project and i have more information how to reproduce this.
[vscode-bug-324.zip](https://github.com/microsoft/vscode-spring-boot-dashboard/files/14902323/vscode-bug-324.zip)


1. When you rename package, for example, rename package com.example.license in license-core to com.example.license2 and click in gradle plugin(Gradle for Java) tab "Reload All Gradle Projects". This will result in duplication of controller methods and beans.
![image](https://github.com/microsoft/vscode-spring-boot-dashboard/assets/2545203/d36593e1-a4cf-440e-9332-5c0034b6b18a)

2. Update spring-boot plugin in build.gradle from "id 'org.springframework.boot' version '3.2.2' apply false" to 3.2.4 and click "Reload All Gradle Projects". This will result in duplication of the subproject
![image](https://github.com/microsoft/vscode-spring-boot-dashboard/assets/2545203/a6c5d10f-40b0-470c-bdd1-b986aedb167a)

P.S. Re-opening vscode helps with duplicates

**Comment by martinlippert** [comment] 2024-04-11 10:08
Thanks for attaching the sample project and the steps how to reproduce the issue. Unfortunately, using the sample project and following your steps, I can't reproduce this on my end.

I have two additional thoughts that could provide more insights here, would be great if you could run through those two things.

1) once the beans and mappings appear duplicated on the dashboard views, what happens if you press `Cmd-T` (`Go to Symbols in Workspace...`). Do the request mapping symbols appear duplicated there as well?

2) can you add this to your `settings.json`:

```
"spring-boot.ls.logfile": "<some-path>/vscode-log.txt"
```

and replace `<some-path>` with a path that makes sense on your machine? That would be awesome. Next time you run VSCode, it will dump the log output of the spring boot language server to that file. Once that works, can you clean up the file, then run the steps to reproduce the issue, and than attach the log output here? That would be awesome.

Maybe this reveals more insights about why those symbols appear duplicated.

**Comment by martinlippert** [comment] 2024-04-16 08:03
@Sorreldd Any news from your side with regards to the thoughts I put in the previous comment?

**Comment by Sorreldd** [comment] 2024-04-16 09:00
Sorry for the long answer.
This is log file, I divided it and commented each step.
[vscode-log.txt](https://github.com/microsoft/vscode-spring-boot-dashboard/files/14994342/vscode-log.txt)
Also my settings.json. Just in case
[settings.json](https://github.com/microsoft/vscode-spring-boot-dashboard/files/14994351/settings.json)

**Comment by martinlippert** [comment] 2024-04-16 13:55
Thanks a lot for the additional details, that helps a lot. I can reproduce this within VSCode now, easy to reproduce by just renaming a random Java source file in VSCode that contains symbols. After the rename operation, the old symbol sticks around. Things get worse if you rename whole packages, then the old symbols stick around and new symbols are sometimes not even created (especially if the files from the package or not opened in editors).

Will continue to work on this as part of https://github.com/spring-projects/sts4/issues/1231, since this is caused by the underlying Spring Tools that are used by the dashboard to get those beans and request mapping items: https://github.com/spring-projects/sts4/issues/1231

Closing this one here as a duplicate of the one mentioned above. Please follow that one to keep track and maybe respond to further questions.

**Closed by martinlippert** 2024-04-16 13:55 UTC

**Comment by martinlippert** [comment] 2024-04-17 11:29
Some initial results from debugging this: https://github.com/spring-projects/sts4/issues/1231#issuecomment-2061040677.

@Sorreldd, can you disable the `Project Manager for Java` extension from your workspace to see if that makes a difference? Would be interesting to know.

**Comment by Sorreldd** [comment] 2024-04-17 11:45
Project Manager for Java - disabled
And I didn't see any changes
[vscode-log.txt](https://github.com/microsoft/vscode-spring-boot-dashboard/files/15010326/vscode-log.txt)

**Comment by martinlippert** [comment] 2024-04-17 13:27
Thanks for checking and the feedback, looks like more stuff is going wrong here...

**Comment by martinlippert** [comment] 2024-04-22 13:46
@Sorreldd, the issue in the Spring Boot Tools extension should be fixed as well now. If you switch both extensions (`Project Manager for Java` + `Spring Boot Tools`) to the latest pre-release, renaming packages should work now without duplicating symbols or keeping old symbols around.
